# Generated by Django 5.2.17 on 2026-09-26 08:09

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_code_hash', models.CharField(max_length=64, unique=True)),
                ('user_code', models.CharField(max_length=9, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=accounts.models._cli_login_expiry)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cli_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_cli_login',
            },
        ),
    ]
