# Generated by Django 5.2.17 on 2026-09-25 13:30

import django.db.models.deletion
import sre.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=255)),
                ('uptrace_exception_id', models.CharField(blank=True, default='', max_length=255)),
                ('temporal_workflow_id', models.CharField(max_length=255, unique=True)),
                ('raw_webhook_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Running'), ('no_anomaly', 'No anomaly confirmed'), ('new_playbook_created', 'New playbook created'), ('awaiting_approval', 'Awaiting human approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('advisory_complete', 'Advisory complete')], default='running', max_length=32)),
                ('classification', models.JSONField(blank=True, null=True)),
                ('diagnosis_report', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sre_incident_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('self_hosted', 'Self-hosted (OpenAI-compatible)'), ('jev_cloudflare', 'Jev (Cloudflare Workers AI)')], max_length=32)),
                ('model', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True, default='')),
                ('api_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('extra_config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sre_llm_provider_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('failing', 'Failing')], default='unconfirmed', max_length=32)),
                ('execution_mode_override', models.CharField(blank=True, choices=[('autonomous', 'Autonomous'), ('draft_only', 'Draft only'), ('advisory_only', 'Advisory only')], max_length=32, null=True)),
                ('consecutive_failure_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_incident_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_playbook', to='sre.incidentrun')),
            ],
            options={
                'db_table': 'sre_playbook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='matched_playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_runs', to='sre.playbook'),
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_mode', models.CharField(choices=[('autonomous', 'Autonomous'), ('draft_only', 'Draft only'), ('advisory_only', 'Advisory only')], max_length=32)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('rejected', 'Rejected'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pr_url', models.URLField(blank=True, default='')),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_run', to='sre.incidentrun')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='sre.playbook')),
            ],
            options={
                'db_table': 'sre_playbook_run',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_installation_id', models.CharField(max_length=64)),
                ('github_repo_owner', models.CharField(max_length=255)),
                ('github_repo_name', models.CharField(max_length=255)),
                ('github_default_branch', models.CharField(default='main', max_length=100)),
                ('uptrace_webhook_secret', models.CharField(default=sre.models._new_webhook_secret, max_length=128)),
                ('uptrace_source_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('default_execution_mode', models.CharField(choices=[('autonomous', 'Autonomous'), ('draft_only', 'Draft only'), ('advisory_only', 'Advisory only')], default='draft_only', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_llm_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_default_for', to='sre.llmproviderconfig')),
            ],
            options={
                'db_table': 'sre_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='playbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='sre.project'),
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_runs', to='sre.project'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('viewer', 'Viewer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='sre.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sre_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sre_project_membership',
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='sre_projects', through='sre.ProjectMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlaybookExecutionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('generated_steps', models.JSONField(default=list)),
                ('previous_attempt_feedback', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('error_output', models.TextField(blank=True, default='')),
                ('branch_name', models.CharField(blank=True, default='', max_length=255)),
                ('langfuse_trace_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playbook_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='sre.playbookrun')),
            ],
            options={
                'db_table': 'sre_playbook_execution_attempt',
                'ordering': ['attempt_number'],
                'unique_together': {('playbook_run', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='LLMStepOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('anomaly_double_check', 'Anomaly double-check'), ('bug_classification', 'Bug classification'), ('playbook_similarity_judge', 'Playbook similarity judge'), ('playbook_creation', 'Playbook creation'), ('playbook_execution', 'Playbook execution')], max_length=64)),
                ('llm_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sre.llmproviderconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_overrides', to='sre.project')),
            ],
            options={
                'db_table': 'sre_llm_step_override',
                'unique_together': {('project', 'step')},
            },
        ),
    ]
