# Generated by Django 5.2.17 on 2026-09-25 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=64)),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to='sre.incidentrun')),
            ],
            options={
                'db_table': 'sre_llm_usage',
                'ordering': ['created_at'],
            },
        ),
    ]
