# Generated by Django 5.2.17 on 2026-09-25 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0002_llmusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(max_length=64)),
                ('account_login', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_installations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sre_github_installation',
                'ordering': ['account_login'],
                'unique_together': {('user', 'installation_id')},
            },
        ),
    ]
