# Generated by Django 5.2.17 on 2026-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0003_githubinstallation'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='generate_tests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='generate_tests',
            field=models.BooleanField(default=True),
        ),
    ]
