# Generated by Django 5.2.17 on 2026-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0004_generate_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusage',
            name='billed_to',
            field=models.CharField(db_index=True, default='user', max_length=16),
        ),
    ]
