# Generated by Django 5.2.17 on 2026-09-26 01:31

from django.db import migrations, models


def relabel_rejected(apps, schema_editor):
    """Incidents whose fix was rejected used to be marked failed."""
    IncidentRun = apps.get_model("sre", "IncidentRun")
    IncidentRun.objects.filter(status="failed", playbook_run__status="rejected").update(status="rejected")


def unlabel_rejected(apps, schema_editor):
    IncidentRun = apps.get_model("sre", "IncidentRun")
    IncidentRun.objects.filter(status="rejected").update(status="failed")


class Migration(migrations.Migration):

    dependencies = [
        ("sre", "0005_llmusage_billed_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("no_anomaly", "No anomaly confirmed"),
                    ("new_playbook_created", "New playbook created"),
                    ("awaiting_approval", "Awaiting human approval"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("rejected", "Rejected (PR not merged)"),
                    ("advisory_complete", "Advisory complete"),
                ],
                default="running",
                max_length=32,
            ),
        ),
        migrations.RunPython(relabel_rejected, unlabel_rejected),
    ]
