# Generated by Django 5.2.17 on 2026-09-26 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0008_backfill_personal_orgs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentrun',
            name='telemetry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='UptraceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('api_base_url', models.URLField()),
                ('token_encrypted', models.BinaryField(blank=True, default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptrace_credentials', to='sre.organization')),
            ],
            options={
                'db_table': 'sre_uptrace_credential',
                'ordering': ['created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='uptrace_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sre.uptracecredential'),
        ),
    ]
