# Generated by Django 5.2.17 on 2026-09-26 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0009_uptrace_credentials_and_telemetry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='playbook',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbook',
            name='is_generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playbook',
            name='legacy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playbook',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='sre.organization'),
        ),
        migrations.AddField(
            model_name='playbook',
            name='origin',
            field=models.CharField(choices=[('builtin', 'Built-in'), ('agent', 'Written by the agent'), ('human', 'Written by a person')], default='agent', max_length=16),
        ),
        migrations.AddField(
            model_name='playbook',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='playbook',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to='sre.project'),
        ),
    ]
