# Generated by Django 5.2.17 on 2026-09-26 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0011_backfill_playbook_orgs_and_seed_builtins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookexecutionattempt',
            name='runbook_draft',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Runbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', max_length=255)),
                ('keywords', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('confirmed', 'Confirmed'), ('failing', 'Failing')], default='unconfirmed', max_length=32)),
                ('consecutive_failure_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(choices=[('agent', "Saved from the agent's fix"), ('human', 'Written by a person'), ('migrated', 'Converted from an old, specific playbook')], default='agent', max_length=16)),
                ('repo_owner', models.CharField(blank=True, default='', max_length=255)),
                ('repo_name', models.CharField(blank=True, default='', max_length=255)),
                ('service_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runbooks', to='sre.playbook')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runbooks', to='sre.project')),
                ('source_playbook_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runbook', to='sre.playbookrun')),
            ],
            options={
                'db_table': 'sre_runbook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='matched_runbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_runs', to='sre.runbook'),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='runbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='sre.runbook'),
        ),
    ]
