# Generated by Django 5.2.17 on 2026-09-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sre", "0012_runbooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="otel_token_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
