# Generated by Django 5.2.17 on 2026-09-26 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0012_runbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentrun',
            name='parent_incident_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_incident_runs', to='sre.incidentrun'),
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='root_cause',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='source',
            field=models.CharField(choices=[('alert', 'Uptrace alert'), ('linked', "Linked from another project's incident"), ('scan', 'Remediation agent finding')], default='alert', max_length=16),
        ),
        migrations.AddField(
            model_name='project',
            name='service_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='incidentrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('no_anomaly', 'No anomaly confirmed'), ('new_playbook_created', 'New playbook created'), ('awaiting_approval', 'Awaiting human approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rejected', 'Rejected (PR not merged)'), ('advisory_complete', 'Advisory complete'), ('delegated', 'Delegated to another project')], default='running', max_length=32),
        ),
        migrations.CreateModel(
            name='ServiceGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=128)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_graphs', to='sre.organization')),
            ],
            options={
                'db_table': 'sre_service_graph',
                'unique_together': {('organization', 'source')},
            },
        ),
        migrations.CreateModel(
            name='ServiceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('service', 'Instrumented service'), ('system', 'Dependency or uninstrumented client')], default='service', max_length=16)),
                ('repo_url', models.CharField(blank=True, default='', max_length=500)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='sre.servicegraph')),
            ],
            options={
                'db_table': 'sre_service_node',
                'ordering': ['name'],
                'unique_together': {('graph', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('duration_avg_ms', models.FloatField(default=0)),
                ('duration_max_ms', models.FloatField(default=0)),
                ('rate_per_min', models.FloatField(default=0)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='sre.servicegraph')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='sre.servicenode')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='sre.servicenode')),
            ],
            options={
                'db_table': 'sre_service_edge',
                'unique_together': {('client', 'server', 'type')},
            },
        ),
    ]
