# Generated by Django 5.2.17 on 2026-09-26 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0013_service_mesh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentrun',
            name='execution_mode_cap',
            field=models.CharField(blank=True, choices=[('autonomous', 'Autonomous'), ('draft_only', 'Draft only'), ('advisory_only', 'Advisory only')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='scan_kind',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='llmstepoverride',
            name='step',
            field=models.CharField(choices=[('anomaly_double_check', 'Anomaly double-check'), ('bug_classification', 'Bug classification'), ('playbook_similarity_judge', 'Playbook similarity judge'), ('playbook_creation', 'Playbook creation'), ('playbook_execution', 'Playbook execution'), ('repository_scan', 'Repository scan (remediation agents)')], max_length=64),
        ),
        migrations.AlterField(
            model_name='llmusage',
            name='incident_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to='sre.incidentrun'),
        ),
        migrations.CreateModel(
            name='RemediationAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('playbook_sweep', 'Playbook sweep'), ('runbook_variant', 'Runbook variant hunt'), ('find_quiet', 'Quiet errors from Uptrace')], default='playbook_sweep', max_length=32)),
                ('trigger', models.CharField(choices=[('on_merge', 'A PR merged into the default branch'), ('branch_watch', 'A push to a watched branch'), ('schedule', 'A cron schedule')], default='on_merge', max_length=32)),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=100)),
                ('branch_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('execution_mode', models.CharField(choices=[('autonomous', 'Autonomous'), ('draft_only', 'Draft only'), ('advisory_only', 'Advisory only')], default='advisory_only', max_length=32)),
                ('max_findings_per_repo', models.PositiveSmallIntegerField(default=3)),
                ('monthly_token_budget', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_agents', to='sre.organization')),
                ('playbooks', models.ManyToManyField(blank=True, related_name='remediation_agents', to='sre.playbook')),
                ('projects', models.ManyToManyField(blank=True, related_name='remediation_agents', to='sre.project')),
            ],
            options={
                'db_table': 'sre_remediation_agent',
                'ordering': ['created_at'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScanRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('base_sha', models.CharField(blank=True, default='', max_length=64)),
                ('head_sha', models.CharField(blank=True, default='', max_length=64)),
                ('finding_count', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_repos', to='sre.project')),
            ],
            options={
                'db_table': 'sre_scan_repo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='llmusage',
            name='scan_repo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage', to='sre.scanrepo'),
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('manual', 'Run by hand'), ('on_merge', 'A PR merged into the default branch'), ('branch_watch', 'A push to a watched branch'), ('schedule', 'A cron schedule')], max_length=32)),
                ('trigger_ref', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Some repos failed'), ('failed', 'Failed')], default='running', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('temporal_workflow_id', models.CharField(max_length=255, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_runs', to='sre.remediationagent')),
            ],
            options={
                'db_table': 'sre_scan_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='scanrepo',
            name='scan_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='sre.scanrun'),
        ),
        migrations.AddField(
            model_name='incidentrun',
            name='scan_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_runs', to='sre.scanrun'),
        ),
        migrations.AlterUniqueTogether(
            name='scanrepo',
            unique_together={('scan_run', 'project')},
        ),
    ]
