# Generated by Django 5.2.17 on 2026-09-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0014_remediation_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uptrace_dsn_encrypted',
            field=models.BinaryField(blank=True, default=b''),
        ),
        migrations.AddField(
            model_name='project',
            name='uptrace_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='uptrace_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='uptrace_project_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='uptrace_status',
            field=models.CharField(blank=True, choices=[('', 'Not managed'), ('provisioning', 'Setting up'), ('ready', 'Ready'), ('error', 'Error')], default='', max_length=16),
        ),
    ]
