# Generated by Django 5.2.17 on 2026-09-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0015_managed_uptrace'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='platform_preset',
            field=models.CharField(default='openai_jev', max_length=32),
        ),
    ]
