# Generated by Django 5.2.17 on 2026-09-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0016_project_platform_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusage',
            name='cached_input_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='llmusage',
            name='turn',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
