# Generated by Django 5.2.17 on 2026-09-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0017_llm_usage_cached_and_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookrun',
            name='covered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sre.playbookrun'),
        ),
        migrations.AddField(
            model_name='playbookrun',
            name='mode_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='remediationagent',
            name='code_findings_open_prs',
            field=models.BooleanField(default=False),
        ),
    ]
