# Generated by Django 5.2.17 on 2026-09-26 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sre', '0018_agent_code_finding_prs'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanrun',
            name='runbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sre.runbook'),
        ),
        migrations.AlterField(
            model_name='scanrun',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Run by hand'), ('on_merge', 'A PR merged into the default branch'), ('branch_watch', 'A push to a watched branch'), ('schedule', 'A cron schedule'), ('fix_merged', 'A fix merged in another repo')], max_length=32),
        ),
    ]
